version: '3.8'
services:
  db:
    image: mysql/mysql-server:latest
    container_name: my-mysql
    restart: always
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=123
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-volume:/tmp
volumes:
  mysql-volume:
    driver: local
#    driver_opts:
#       o: bind
#       type: none
#       device: /home/silvio/24/java/MySQL
